-- run_test.py: invoking following command in '/home/dorson/Documents/github/Doe/src/doe_control':
 - /opt/ros/jazzy/bin/ament_pep257 --xunit-file /home/dorson/Documents/github/Doe/src/doe_control/build/doe_control/test_results/doe_control/pep257.xunit.xml

checking ./install/_local_setup_util_ps1.py
checking ./install/_local_setup_util_sh.py
No problems found


-- run_test.py: return code 0
-- run_test.py: verify result file '/home/dorson/Documents/github/Doe/src/doe_control/build/doe_control/test_results/doe_control/pep257.xunit.xml'
